### ISSUE TITLE
Problems with short closures ( /> )

### ISSUE THREAD

**Issue by john-dev** [revnode/xml#2]
Hello,

i would love to use that class, but somehow, short closures/empty close tag (<.. /> instead of <..>..</..>) are interpreted wrong.
I would love to see a fix here.

example xml:
http://bagit.logpic.com/12345.mets.xml

cheers,
John

**Comment by revnode** [comment]
Hey John!

I just pushed support for short closures. I added your xml file to the repo under the test folder. If something doesn't work, let me know.

Thanks!

Marat

**Comment by john-dev** [comment]
Hey Marat,

thanks for the quick reply.
I updated my verion, but it didn't fix the problem.
The structure is still broken!

Cheers,
John

**Comment by revnode** [comment]
Hey John!

I'm going to need a bit more info. The XML file you provided was working on my machine.

Thanks!

- Marat
